### ISSUE TITLE
Adding device gives error

### ISSUE THREAD

**Issue by pimagical** [philip1986/pimatic-led-light#1]
1. Added iwy-light-master 0.0.2-1 with use of the GUI plugin page. 
2. restart
3. Commit device in config gives error message Cannot find module '/home/pi/pimatic-app/node_modules/pimatic-iwy-light-master/iwy-light-master-schema.coffee'
   
   {
     "id": "IwyLightMaster",
     "name": "IwyLightMaster",
     "class": "IwyLightMaster",
     "location": "living room",
     "addr": "xxx.xxx.xxx.xxx",
     "device": "wifi370"
   },

**Comment by philip1986** [comment]
I fix this issue you can install the latest version of the plugin via `npm i pimatic-led-light`. The plugin is also renamed now, so you will have to adjust your config. 

```
   {
      "id": "some_id",
      "name": "some_name",
      "class": "LedLight",
      "location": "living room",
      "addr": "xxx.xxx.xxx.xxx"
      "device": "iwy-master" | "wifi370"
    }
```
