### ISSUE TITLE
Toggle switch event gets lost if color picker is open

### ISSUE THREAD

**Issue by mwittig** [philip1986/pimatic-led-light#10]
I have noticed a bug with the color picker: If the color picker is open and you toggle the switch the switch event is not fired or gets lost somehow. As a result the UI switch is switched but the switch action is not performed.

**Comment by philip1986** [comment]
Is this still the case?

**Comment by mwittig** [comment]
Yes, this is still the case,

**Comment by philip1986** [comment]
Its fixed now at the Master (by this PR https://github.com/philip1986/pimatic-led-light/pull/30). I will soon publish a new version on npm.

**Comment by mwittig** [comment]
Great. Thanks!
