### ISSUE TITLE
setColor in color_action.coffee

### ISSUE THREAD

**Issue by tester22** [philip1986/pimatic-led-light#19]
Hi,

This code breaks rules for me: 
https://github.com/philip1986/pimatic-led-light/blob/master/predicates_and_actions/color_action.coffee#L36

What is the purpose of this function?

**Comment by philip1986** [comment]
Hi,

the purpose is to change the color of the light device. So you could have a rule like:
"if ... than set device to red "

Can you please provide an example of the breaking rules.

**Comment by tester22** [comment]
Hi. 

My rule is as simple as:

set blinkstick to red

The error message is setColor: is undefined.

When removing this code the rule works as expected (changeing color to red).

**Comment by tester22** [comment]
Another user seems to have the same issue after the last update: http://forum.pimatic.org/topic/687/problems-with-color-change-pimatic-led-light-plugin-with-milight

**Comment by philip1986** [comment]
@tester22 you are right the code at this line is broken. It will be fixed soon.

**Comment by philip1986** [comment]
fixed by https://github.com/philip1986/pimatic-led-light/pull/25
