### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by michbeck100** [philip1986/pimatic-led-light#34]
SInce there were no commits sind Oct. 5th i'd like to know, if this project is still maintained by anyone? I've added this [pull request](https://github.com/philip1986/pimatic-led-light/pull/33), but there was no reaction since then.

**Comment by mwittig** [comment]
@philip1986 If you're too busy, I am happy to help with maintaining the project. 
May be you can be you can add as co-maintainer on github and npmjs? This would be great.

**Comment by philip1986** [comment]
Sorry, I didn`t have the much time to take care about it. But I added @mwittig as maintainer, he take care about your PR.
