### ISSUE TITLE
Wfif370 exception on white mode

### ISSUE THREAD

**Issue by mwittig** [philip1986/pimatic-led-light#37]
if i press the white X on the color wheel (which i dont really know what its for because one can switch it of with the switch on the right) pimatic produces a long error which you can also see in the video https://youtu.be/Agt1bTkHmhw

See also https://github.com/philip1986/pimatic-led-light/issues/27

**Comment by mwittig** [comment]
@thymian I have written a mockup server to see the byte sequences sent to the Wifi370. As far as I can see the byte sequences sent are OK, but may be it is the response from Wifi370 causing the error. Can you please send me there error message with the full statck trace? Thanks.

**Comment by philip1986** [comment]
I published a "driver" [fix](https://github.com/philip1986/iwy_master/pull/4/files). White updating the dependency iwy_master to 0.2.3, pressing the white X should change the color to cold white. 

Not sure if this solves the issue!

**Comment by thymian** [comment]
I have no idea what changed but I cant reproduce the error. So this Issue is not about the error message but about WHAT to do with the button. I think just removing it for wifi370 is better than turning all RGB LEDs to 100% because one can do this easy with the slider/ colorpicker.

**Comment by philip1986** [comment]
I don't thing its a good idea to introduces device specific logic at the UI layer, because it can quickly become messy.

**Comment by mwittig** [comment]
published pimatic-led-light@0.3.2 which contains iwy_master 0.2.3

**Comment by mwittig** [comment]
I am closing this now. Please re-open if the the issue pops up again. Having a different UI for RGB light in contrast to RGBW is a seperate topic. If you like please open a feature request for it. Would also nice if we can support WW/CW lamps in the future :)
