### ISSUE TITLE
Improve debounce result handling on Milight driver

### ISSUE THREAD

**Issue by mwittig** [philip1986/pimatic-led-light#41]
Need to return the resilt of the called function

**Comment by philip1986** [comment]
Like I already mentioned [here](https://github.com/philip1986/pimatic-led-light/issues/35#issuecomment-168046364), in my opinion we should remove the debounce logic here!

**Comment by mwittig** [comment]
As discussed on #35 I have reverted the commit. I am closing this ticket for now.

**Comment by philip1986** [comment]
:+1:
