### ISSUE TITLE
Layout problem in frontend 

### ISSUE THREAD

**Issue by iMarvinS** [philip1986/pimatic-led-light#45]
It seems like the layout of the widget in the mobile frontend does have some problems on smaller devices (iPhone 6 for example).
Can this be fixed so that the slider and the color selector are both in the same row separated by a small gap and that the switch is positioned in the second row floating left?
Currently it is really hard to adjust the brightness because the silder is just too small.

![bildschirmfoto 2016-01-07 um 15 02 51](https://cloud.githubusercontent.com/assets/7142039/12172297/605f23d0-b550-11e5-83d4-5ff7d74fc7c8.png)

**Comment by philip1986** [comment]
I am currently working on it see [here](http://forum.pimatic.org/topic/332/plugin-for-wifi-controlled-led-light-iwy-light/106)

**Comment by iMarvinS** [comment]
That looks promising! Issue can be closed now.
