### ISSUE TITLE
Integration of Milight; Separation into device types

### ISSUE THREAD

**Issue by mwittig** [philip1986/pimatic-led-light#5]
I have forked from master yesterday to integrate Milight. Pull request follows

**Comment by mwittig** [comment]
Just a few words about my code changes
- I have created another device class "Milight" we uses the same template as LedLight
- I have left the implementation of LedLight untouched, but you may want to consider the separation of Iwy and Wifi370 modes into two device classes. Note, you can also use inheritance as part of the device implementation, say a LedLightBase class for common functionality
- As you can see I have split the plugin and device config into two files:
  - led-light-schema.coffee defining plugin configuration properties (no properties, currently)
    - device-config-schema.coffee defining device properties

**Comment by mwittig** [comment]
The following configuration works file for me

Plugin:

```
{
      "plugin": "led-light"
}
```

Device:

```
{
      "id": "led1",
      "class": "Milight",
      "name": "Milight",
      "addr": "192.168.178.64",
      "zone": 1,
      "location": "Kitchen",
      "device": "iwy-master"
},
{
      "id": "led2",
      "class": "LedLight",
      "name": "LED Light",
      "addr": "192.168.178.67",
      "location": "Bedroom",
      "device": "iwy-master"
}
```

**Comment by philip1986** [comment]
checkout https://github.com/philip1986/pimatic-led-light/pull/7

**Comment by philip1986** [comment]
Done by https://github.com/philip1986/pimatic-led-light/pull/9
