### ISSUE TITLE
When installing hue branch hyperion stops working

### ISSUE THREAD

**Issue by djmvt** [philip1986/pimatic-led-light#50]
![knipsel](https://cloud.githubusercontent.com/assets/16620825/12863605/b115b048-cc78-11e5-882f-45a0debd4e41.JPG)
Getting this error after installing the hue branch on pimatic.
any clue what is going wrong?

**Comment by djmvt** [comment]
if I remove es6-promise from node_modules (in pimatic-led-light/node_modules) hyperion starts, obviously Hue stops working then. so it's either hyperion or hue.

**Comment by michbeck100** [comment]
should be fixed now, so this issue can be closed.

**Comment by mwittig** [comment]
Should have been fixed with v0.9.1. No feedback from @djmvt
