### ISSUE TITLE
Milight led strip WW

### ISSUE THREAD

**Issue by jochem4207** [philip1986/pimatic-led-light#54]
Is it supposed to work with WW strips to? using this kind of controllers: https://imgur.com/a/GxCcA

My config is like this:

```
 {
      "id": "MiLight1",
      "name": "MiLight Room",
      "class": "Milight",
      "addr": "192.168.1.2",
      "zone": 1
 },
```

Tried also zone 0 to turn all on of.

No response from my led strip. Multiple apps are working fine via the wifi bridge (v4) and the RF remote works fine to.

**Comment by mwittig** [comment]
Hi, Turning the strip on/off should work. Dimming is likely to have no effect as different control code have to be used for WW as opposed to RGB. There is a pending PR for WW support and I'll check if we can integrate this soon.

**Comment by jochem4207** [comment]
@mwittig Cool, thank you. Then I probably have some config error somewhere. Do you know if there is a way to read out the milight wifi box? to see if it gets commands from pimatic/other apps?

**Comment by mwittig** [comment]
@jochem4207 You can sniff the IP traffic using WireShark or alike, but this will only tell you whether or not the UDP command packets are sent to the WifiBox. I haven't heard about facility to read out the wifi box itself. As you said "Multiple apps are working fine via the wifi bridge (v4)" I think it should also work with pimatic. If you can control the strip with your smartphone (using the Milight app) it should also work with pimatic, given that you have set the correct IP address.

**Comment by jochem4207** [comment]
@mwittig thanks for the info! will close it issue now as it is double and there is already a PR pending.
