### ISSUE TITLE
Rule error this.device.getDimlevel is not a function

### ISSUE THREAD

**Issue by stingone** [philip1986/pimatic-led-light#65]
After the latest update pimatic/led light i get the error that dimlevel is not a function. looks like it only occurs with led-light devices.

**Comment by benbeton** [comment]
same here.

my rule:

_dim Lampe Galerie to 10% and turn on Lampe Galerie_

gives me the error:

_Error on evaluation of rule condition of rule licht-an-galerie-bewegung-nachts: this.device.getDimlevel is not a function_
_rule licht-an-galerie-bewegung-nachts error executing an action: this.device.getDimlevel is not a function_

I’m using led-light 0.9.1

**Comment by mwittig** [comment]
See https://forum.pimatic.org/topic/2127/error-rule-after-update/10
Please let me know, which device types do you use, i.e., IwyMaster, Milight, MilightRF24, Wifi370, Blinkstick, DummyLedLight, or HyperionLedLight?

**Comment by mwittig** [comment]
Fixed in 0.9.2.
